# Generated by Django 2.2 on 2021-05-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newarrivals',
            options={'verbose_name': 'NewArrivals', 'verbose_name_plural': 'New Arrivals'},
        ),
        migrations.AlterModelOptions(
            name='toppicks',
            options={'verbose_name': 'TopPicks', 'verbose_name_plural': 'Top Picks'},
        ),
        migrations.AlterField(
            model_name='toppicks',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
