# Generated by Django 2.2 on 2021-05-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love_apps', '0002_auto_20210502_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comingsoon',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='newarrivals',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
