# Generated by Django 2.2 on 2021-05-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love_apps', '0003_auto_20210502_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_image', models.ImageField(upload_to='static/images/')),
            ],
            options={
                'verbose_name': 'BestSellers',
                'verbose_name_plural': 'Best Sellers',
            },
        ),
    ]
