# Generated by Django 2.2 on 2021-05-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('love_apps', '0004_bestseller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestseller',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='bestseller',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='bestseller',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='comingsoon',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='comingsoon',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='comingsoon',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='newarrivals',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='newarrivals',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='newarrivals',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='toppicks',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='toppicks',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='toppicks',
            old_name='Price',
            new_name='price',
        ),
    ]
