# Generated by Django 2.2 on 2021-05-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love_apps', '0005_auto_20210502_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestseller',
            name='availabilty',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bestseller',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='comingsoon',
            name='availabilty',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='comingsoon',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='newarrivals',
            name='availabilty',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='newarrivals',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='availabilty',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='toppicks',
            name='availabilty',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='toppicks',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
