# Generated by Django 2.2 on 2021-05-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love_apps', '0006_auto_20210505_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestseller',
            name='product_image',
            field=models.ImageField(upload_to='images/bestseller'),
        ),
        migrations.AlterField(
            model_name='comingsoon',
            name='product_image',
            field=models.ImageField(upload_to='images/coming'),
        ),
        migrations.AlterField(
            model_name='newarrivals',
            name='product_image',
            field=models.ImageField(upload_to='images/newarrivals'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='images/product'),
        ),
        migrations.AlterField(
            model_name='toppicks',
            name='product_image',
            field=models.ImageField(upload_to='images/toppicks'),
        ),
    ]
